### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DenielWorld** [padreon/SimpleCape#1]
Register custom permission for each uploaded cape. Thanks.

**Comment by padreon** [comment]
You mean like this? 
permission: simple.cape.diamond
command: /cape diamond

**Comment by DenielWorld** [comment]
Yes, also I am having an issue. The cape format must be exactly 8192 bytes, how would I convert my cape pngs to that?

**Comment by padreon** [comment]
for set cape to player you must have valid cape
```
$capeData = $player->getSkin()->getCapeData();
$bytes = strlen($capeData);
var_dump($bytes); //output 8192
```

**Comment by DenielWorld** [comment]
How do I make my own custom cape that would be valid, and could you give me some examples of valid capes?

**Comment by padreon** [comment]
https://github.com/padreon/SimpleCape/blob/master/resources/cape.png

**Comment by DenielWorld** [comment]
Well that doesnt give me much explanation

**Comment by padreon** [comment]
convert png to skindata and get bytes with strlen

**Comment by padreon** [comment]
[update permission](https://github.com/padreon/SimpleCape/pull/2)
