### ISSUE TITLE
Cape does not appear

### ISSUE THREAD

**Issue by ghost** [padreon/SimpleCape#11]
I have test with just SimpleCape like plugin (latest github version with default files and config).
When i made /cape cape (cape is the name of défault cape), my skin have an actualisation glitch but after the cape does not appears.
I test with steve skin and personnal skin (two don't custom).
I have also gd enable

Please help me

**Comment by padreon** [comment]
can you send the error log?

can you check with the default [cape](https://github.com/padreon/SimpleCape/blob/master/resources/cape.png)?

**Comment by ghost** [comment]
There is no error that appears in the console and I tested with the default cape

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/61470324/108084465-7ff1c380-7074-11eb-8143-3548376b9842.mp4

**Comment by padreon** [comment]
![image](https://user-images.githubusercontent.com/19891373/108118104-d4c72580-70d8-11eb-8acd-cc69a26e7fbf.png)

Simple cape is work well
How I reproduce:

1. install server
2. compile bin
3. install the plugin from poggit
4. join the server
5. `/cape cape` and `/cape remove` work very well for me

**Comment by ghost** [comment]
I have test with just SimpleCape (latest version poggit) ans latest version of pmmp.
and there is no change, the cape does not appears.

Could you give me your bin folder that i test if it's not my php settings issue ?

**Comment by padreon** [comment]
I'm using [php build script](https://github.com/pmmp/php-build-scripts) from Pmmp
`./installer.sh`
`./compile.sh ` with argument you want, if you want to enable gd you should follow this [tutorial](https://forums.pmmp.io/threads/how-to-install-gd-lib-in-php-binary.4372/)

**Comment by ghost** [comment]
How php build script work on windows to compile php for linux server

**Comment by ghost** [comment]
Or, can you just send me your bin ?

**Comment by padreon** [comment]
dm me , I don't want my test server IP to spread
