### ISSUE TITLE
Permission Bug

### ISSUE THREAD

**Issue by xKurt** [padreon/SimpleCape#12]
Hello,

Permission doesn't work
I added **simplecape.name.guest** to a **Guest** rank and they still can't access the cape
"You don't have permission to use this cape"

**Comment by inxomnyaa** [comment]
`simplecape.name.<YOU PUT THE NAME OF THE CAPE HERE>`

**Comment by xKurt** [comment]
Oh okay,
Thanks btw, and can you change it on the plugin description? So people will not ask

**Comment by inxomnyaa** [comment]
![image](https://user-images.githubusercontent.com/8733998/108628764-f1f34f80-745c-11eb-843c-c414017fa3aa.png)
it already is and obviously states what to do

**Comment by xKurt** [comment]
> `simplecape.name.<YOU PUT THE NAME OF THE CAPE HERE>`

oop u said `simplecape.YOU PUT THE NAME OF THE CAPE HERE` earlier

**Comment by xKurt** [comment]
and nope, it still doesn't work

**Comment by thebigsmileXD** [comment]
yes, because i guessed, just like you

**Comment by xKurt21** [comment]
> yes, because i guessed, just like you

?

**Comment by xKurt** [comment]
> Hello,
> 
> Permission doesn't work
> I added **simplecape.name.guest** to a **Guest** rank and they still can't access the cape
> "You don't have permission to use this cape"

It doesn't work
its `guest.png`

Try it for yourself

**Comment by inxomnyaa** [comment]
https://github.com/padreon/SimpleCape/blob/master/src/padreon/SimpleCape/Main.php#L50
is missing the `.` after the `name` whoopsie

sorry for earlier, most times issues like these turn out to be user issues by not properly understanding or reading the howto's. Also, grandma died so i am not in the best mood, sorry if that passed on to you

**Comment by padreon** [comment]
can you try this?
Permission : `simplecape.cape.cape`
Command: `/cape cape`

note:
Use lowercase

**Comment by xKurt** [comment]
> https://github.com/padreon/SimpleCape/blob/master/src/padreon/SimpleCape/Main.php#L50
> is missing the `.` after the `name` whoopsie
> 
> sorry for earlier, most times issues like these turn out to be user issues by not properly understanding or reading the howto's. Also, grandma died so i am not in the best mood, sorry if that passed on to you

Omg its good! Dw and im so sorry to hear of your loss!
Thanku sm
