### ISSUE TITLE
Transparence does'nt work

### ISSUE THREAD

**Issue by Barlaf** [padreon/SimpleCape#3]
All in title.
Try with this cape, all transparent pixel is replace by black pixel
![Cape arc en ciel](https://user-images.githubusercontent.com/26855115/63681461-1d5c9600-c7f6-11e9-936e-484244b56857.png)

PS: add example cape : 
![exemple](https://user-images.githubusercontent.com/26855115/63681489-2baab200-c7f6-11e9-9059-3ecf6dc346bb.png)

**Comment by UnEnanoMas** [comment]
X2
