### ISSUE TITLE
Help for real :v

### ISSUE THREAD

**Issue by VeiledKernel** [padreon/SimpleCape#9]
I was wondering how do I add another cape.png because when I put another cape and I use the command, ex: /cape avalon. then it goes internal server error

![ISSUE SimpleCape](https://user-images.githubusercontent.com/76160267/105489084-4207b680-5ce5-11eb-8e5b-c2776603723b.png)

**Comment by inxomnyaa** [comment]
Cape is too small. Increase image size by factor 2

**Comment by VeiledKernel** [comment]
What does that mean?
I'm bad at english, sorry

**Comment by inxomnyaa** [comment]
Resize image

**Comment by VeiledKernel** [comment]
Umm can you tell me the width and height please

Width:
Height:

**Comment by inxomnyaa** [comment]
Most likely 64x64

**Comment by VeiledKernel** [comment]
Ok man thanks

**Comment by padreon** [comment]
thanks for helped @thebigsmileXD
